import { jsPDF } from 'jspdf';
import type Konva from 'konva';
import type { PedigreeMetadata } from '../types/pedigree';
import { captureCleanDataUrl } from './captureClean';

/**
 * Loads a data URL into an Image to read its natural pixel dimensions.
 * Used so the PDF can preserve the captured pedigree's aspect ratio rather
 * than the (unrelated) on-screen stage aspect ratio.
 */
function loadImageDimensions(
  dataUrl: string
): Promise<{ width: number; height: number }> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = (): void =>
      resolve({ width: img.naturalWidth, height: img.naturalHeight });
    img.onerror = (): void =>
      reject(new Error('Failed to load exported pedigree image'));
    img.src = dataUrl;
  });
}

const MARGIN = 20;
const HEADER_FONT_SIZE = 16;
const BODY_FONT_SIZE = 10;
const FOOTER_FONT_SIZE = 8;

export async function exportToPdf(
  stage: Konva.Stage,
  metadata: PedigreeMetadata
): Promise<void> {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // --- Header ---
  let cursorY = MARGIN;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(HEADER_FONT_SIZE);
  doc.text(metadata.title, MARGIN, cursorY);
  cursorY += 7;

  // Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(BODY_FONT_SIZE);
  const dateStr = new Date(metadata.updatedAt).toLocaleDateString();
  doc.text(`Date: ${dateStr}`, MARGIN, cursorY);
  cursorY += 5;

  // Author / Institution
  if (metadata.author) {
    doc.text(`Author: ${metadata.author}`, MARGIN, cursorY);
    cursorY += 5;
  }
  if (metadata.institution) {
    doc.text(`Institution: ${metadata.institution}`, MARGIN, cursorY);
    cursorY += 5;
  }
  if (metadata.referenceCondition) {
    doc.text(
      `Reference condition: ${metadata.referenceCondition}`,
      MARGIN,
      cursorY
    );
    cursorY += 5;
  }

  // Horizontal rule
  cursorY += 2;
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, cursorY, pageWidth - MARGIN, cursorY);
  cursorY += 5;

  // --- Stage image ---
  // Capture the whole pedigree cleanly (no grid / bounds / selection chrome),
  // independent of the current pan/zoom.
  const dataUrl = captureCleanDataUrl(stage, {
    pixelRatio: 3,
    mimeType: 'image/png',
  });

  const availableWidth = pageWidth - MARGIN * 2;
  const footerHeight = 15;
  const availableHeight = pageHeight - cursorY - footerHeight;

  // Calculate dimensions preserving the captured image's aspect ratio.
  const { width: imageWidth, height: imageHeight } =
    await loadImageDimensions(dataUrl);
  const scale = Math.min(
    availableWidth / imageWidth,
    availableHeight / imageHeight
  );
  const imgWidth = imageWidth * scale;
  const imgHeight = imageHeight * scale;

  // Center horizontally
  const imgX = MARGIN + (availableWidth - imgWidth) / 2;

  doc.addImage(dataUrl, 'PNG', imgX, cursorY, imgWidth, imgHeight);

  // --- Footer ---
  const footerY = pageHeight - MARGIN / 2;
  doc.setFontSize(FOOTER_FONT_SIZE);
  doc.setTextColor(120, 120, 120);

  const footerLeft = 'Generated by Pedigree Canvas';
  const footerRight = new Date().toLocaleDateString();

  doc.text(footerLeft, MARGIN, footerY);
  doc.text(footerRight, pageWidth - MARGIN, footerY, { align: 'right' });

  // --- Save ---
  doc.save(`${metadata.title}.pdf`);
}
